// <auto-generated />
using System;
using LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(PersonalLibraryContext))]
    partial class PersonalLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.Data.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("🏅");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("BadgeId");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Vietnamese");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BookId")
                        .HasName("PK__Books__3DE0C207AE246AD9");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.BookContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("ChapterTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("ContentId")
                        .HasName("PK__BookCont__2907A81E14F582F5");

                    b.HasIndex("BookId");

                    b.ToTable("BookContents");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.BookRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("BookId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsVerifiedReader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Review")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("BookId");

                    b.HasIndex("BookId1");

                    b.HasIndex("UserId", "BookId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BookRating_UserId_BookId");

                    b.ToTable("BookRatings", t =>
                        {
                            t.HasCheckConstraint("CK_BookRating_Stars", "[Stars] >= 1 AND [Stars] <= 5");
                        });
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookmarkId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ContentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookmarkId")
                        .HasName("PK__Bookmark__541A3B7158A17D31");

                    b.HasIndex("BookId");

                    b.HasIndex("ContentId");

                    b.HasIndex(new[] { "UserId", "BookId" }, "IX_Bookmarks_UserId_BookId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Highlight", b =>
                {
                    b.Property<int>("HighlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HighlightId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("yellow");

                    b.Property<int?>("ContentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EndPosition")
                        .HasColumnType("int");

                    b.Property<string>("HighlightedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartPosition")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HighlightId")
                        .HasName("PK__Highligh__B11CEDF0145010ED");

                    b.HasIndex("BookId");

                    b.HasIndex("ContentId");

                    b.HasIndex(new[] { "UserId", "BookId" }, "IX_Highlights_UserId_BookId");

                    b.ToTable("Highlights");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("ContentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EndPosition")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PersonalNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartPosition")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QuoteId");

                    b.HasIndex("BookId");

                    b.HasIndex("ContentId");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("IX_Quotes_IsPublic");

                    b.HasIndex("UserId", "BookId")
                        .HasDatabaseName("IX_Quotes_UserId_BookId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.ReadingHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("MinutesRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId")
                        .HasName("PK__ReadingH__4D7B4ABDCEFE4E28");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("ReadingHistory", (string)null);
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.ReadingProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("ContentId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentChapter")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProgressId")
                        .HasName("PK__ReadingP__BAE29CA5AFA27C7B");

                    b.HasIndex("BookId");

                    b.HasIndex("ContentId");

                    b.HasIndex(new[] { "UserId", "BookId" }, "IX_ReadingProgress_UserId_BookId");

                    b.HasIndex(new[] { "UserId", "BookId" }, "UQ__ReadingP__7456C06DB545D34F")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [BookId] IS NOT NULL");

                    b.ToTable("ReadingProgress", (string)null);
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("user");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CCD05769E");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E44497EC7B")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534E2D44D2B")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.UserBadge", b =>
                {
                    b.Property<int>("UserBadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserBadgeId"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserBadgeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserBadge_UserId_BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.UserLibrary", b =>
                {
                    b.Property<int>("UserLibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLibraryId"));

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsCountedAsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Want to Read");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserLibraryId")
                        .HasName("PK__UserLibr__5B936BDD585C2560");

                    b.HasIndex("BookId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserLibrary_UserId");

                    b.HasIndex(new[] { "UserId", "BookId" }, "UQ__UserLibr__7456C06DA4BA71BB")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [BookId] IS NOT NULL");

                    b.ToTable("UserLibrary", (string)null);
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.UserStats", b =>
                {
                    b.Property<int>("UserStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserStatsId"));

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FavoriteGenre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastReadDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Rank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Mầm Đọc");

                    b.Property<int>("TotalBooksRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalBooksStarted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalMinutesRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPagesRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalWordsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserStatsId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserStats_UserId");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.BookContent", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Book", "Book")
                        .WithMany("BookContents")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__BookConte__BookI__4222D4EF");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.BookRating", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAPI.Data.Models.Book", null)
                        .WithMany("BookRatings")
                        .HasForeignKey("BookId1");

                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithMany("BookRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Bookmark", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Book", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Bookmarks__BookI__571DF1D5");

                    b.HasOne("LibraryAPI.Data.Models.BookContent", "Content")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ContentId")
                        .HasConstraintName("FK__Bookmarks__Conte__5812160E");

                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Bookmarks__UserI__5629CD9C");

                    b.Navigation("Book");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Highlight", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Book", "Book")
                        .WithMany("Highlights")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Highlight__BookI__5CD6CB2B");

                    b.HasOne("LibraryAPI.Data.Models.BookContent", "Content")
                        .WithMany("Highlights")
                        .HasForeignKey("ContentId")
                        .HasConstraintName("FK__Highlight__Conte__5DCAEF64");

                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithMany("Highlights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Highlight__UserI__5BE2A6F2");

                    b.Navigation("Book");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Quote", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LibraryAPI.Data.Models.BookContent", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithMany("Quotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.ReadingHistory", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Book", "Book")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ReadingHi__BookI__6383C8BA");

                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ReadingHi__UserI__628FA481");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.ReadingProgress", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Book", "Book")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ReadingPr__BookI__4F7CD00D");

                    b.HasOne("LibraryAPI.Data.Models.BookContent", "Content")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("ContentId")
                        .HasConstraintName("FK__ReadingPr__Conte__5070F446");

                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ReadingPr__UserI__4E88ABD4");

                    b.Navigation("Book");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.UserBadge", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.UserLibrary", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.Book", "Book")
                        .WithMany("UserLibraries")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserLibra__BookI__47DBAE45");

                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithMany("UserLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserLibra__UserI__46E78A0C");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.UserStats", b =>
                {
                    b.HasOne("LibraryAPI.Data.Models.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("LibraryAPI.Data.Models.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.Book", b =>
                {
                    b.Navigation("BookContents");

                    b.Navigation("BookRatings");

                    b.Navigation("Bookmarks");

                    b.Navigation("Highlights");

                    b.Navigation("ReadingHistories");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("UserLibraries");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.BookContent", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Highlights");

                    b.Navigation("ReadingProgresses");
                });

            modelBuilder.Entity("LibraryAPI.Data.Models.User", b =>
                {
                    b.Navigation("BookRatings");

                    b.Navigation("Bookmarks");

                    b.Navigation("Highlights");

                    b.Navigation("Quotes");

                    b.Navigation("ReadingHistories");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("Stats");

                    b.Navigation("UserBadges");

                    b.Navigation("UserLibraries");
                });
#pragma warning restore 612, 618
        }
    }
}
